---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: Run kubectl version
      ansible.builtin.command:
        cmd: kubectl version --client
      register: kube_version_out
      failed_when: false

    - name: Assert kubectl version
      ansible.builtin.assert:
        that: "'{{ kubectl_version }}' in kube_version_out.stdout"
